# Generated by Django 5.0 on 2023-12-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_tasks_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='notes',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
